title: 
description: A COMPASS 2025 workshop to foster dialogue among researchers, practitioners, and community representatives to generate actionable recommendations, promote equitable and participatory practices, and build resilient interdisciplinary partnerships for a more inclusive future in AI development
theme: minima
markdown: kramdown
